- name: Execute the ovpn_create script
  hosts: all
  become: yes
  tasks:
      - name: Execute the script
        command: python3 /etc/openvpn/getting_close2.py "{{ vpn_userid }}" "{{ mobile_enabled }}" "{{ slack_enabled }}"
  
