---
- name: Remove New Relic Infrastructure Agent 
  hosts: all
  become: yes
  tasks:
    - name: Stop New Relic Infrastructure service
      ansible.builtin.systemd:
        name: newrelic-infra
        state: stopped

    - name: Disable New Relic Infrastructure service
      ansible.builtin.systemd:
        name: newrelic-infra
        enabled: no

    - name: Remove New Relic Infrastructure configuration directory
      ansible.builtin.file:
        path: /etc/newrelic-infra
        state: absent
        force: yes

    - name: Remove New Relic Infrastructure YAML configuration file
      ansible.builtin.file:
        path: /etc/newrelic-infra.yml
        state: absent
        force: yes
        
    - name: Remove New Relic Infrastructure default log directory
      ansible.builtin.file:
        path: /var/log/newrelic-infra
        state: absent
        force: yes

    - name: Remove New Relic Infrastructure systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/newrelic-infra.service
        state: absent
        force: yes
        
    - name: Remove New Relic Infrastructure log file
      ansible.builtin.file:
        path: /var/log/newrelic-infra.log
        state: absent
        force: yes

