---
- name: Vault UserPass Demo
  hosts: all
  gather_facts: false
  vars:
    vault_username: "{{ lookup('env', 'VAULT_USERNAME') }}"
    vault_password: "{{ lookup('env', 'VAULT_PASSWORD') }}"
    vault_secrets:
      - { path: "elasticsearch/certificates" }

  tasks:
    - name: Authenticate with Vault
      uri:
        url: "http://10.16.30.172:8200/v1/auth/userpass/login/{{ vault_username }}"
        method: POST
        body_format: json
        body:
          password: "{{ vault_password }}"
        headers:
          Content-Type: "application/json"
      register: vault_auth_response
      no_log: true

    - name: Store Vault Token
      set_fact:
        vault_token: "{{ vault_auth_response.json.auth.client_token }}"

    - name: Retrieve secrets from Vault
      uri:
        url: "http://10.16.30.172:8200/v1/secret/eng/elasticsearch/certificates"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
      register: retrieved_cert

    - name: Create cert file from Vault secret
      become: true
      copy:
        content: "{{ retrieved_cert.json.data.cert }}"
        dest: /etc/elasticsearch/elastic-certificates.p12
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
      when: retrieved_cert.json.data.cert is defined
