---
- name: Get cert from Vault using AppRole
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get 'cert' from Vault KV1
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/eng/elasticsearch/certificates field=cert engine_version=1 auth_method=approle') }}"
