---
- name: Test Vault KV v1 Lookup via AWX Credential
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Lookup 'cert' from Vault (KV v1)
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/eng/elasticsearch/certificates field=cert engine_version=1') }}"
