---
- name: Install and configure Elasticsearch on Amazon Linux 2023
  hosts: all
  become: yes
  vars:
    es_version: "8.x"
    es_cluster_name: "my-cluster"
    es_node_name: "{{ inventory_hostname }}"
    es_heap_size: "2g"
    es_roles: "{{ es_role_selection.split(',') }}"  # Convert survey input into a list
    es_network_host: "0.0.0.0"
    es_discovery_nodes: ["node1", "node2", "node3"]  # Adjust as needed

  tasks:
    - name: Install required dependencies
      dnf:
        name:
          - dnf-plugins-core
          - java-17-openjdk
        state: present

    - name: Add Elasticsearch YUM repository
      ansible.builtin.yum_repository:
        name: elasticsearch
        description: Elasticsearch repository for {{ es_version }}
        baseurl: https://artifacts.elastic.co/packages/{{ es_version }}/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Elasticsearch
      dnf:
        name: elasticsearch
        state: present

    - name: Configure Elasticsearch
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
      notify: Restart Elasticsearch

    - name: Set JVM heap size
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: '^-Xms.*'
        line: "-Xms{{ es_heap_size }}"
      notify: Restart Elasticsearch

    - name: Set JVM heap size
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: '^-Xmx.*'
        line: "-Xmx{{ es_heap_size }}"
      notify: Restart Elasticsearch

    - name: Enable and start Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

  handlers:
    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
