---
- name: Download revoke_ovpn_cert file from GitHub
  hosts: all
  tasks:
    - name: Download file from GitHub
      copy:
        src: "revoke_ovpn_cert.py"
        dest: "/etc/openvpn/EasyRSA/revoke_ovpn_cert.py"
      register: download_output
      
    - debug: msg="{{ download_output }}"
      

        
- name: Execute the revoke_ovpn_cert script
  hosts: all
  become: yes
  tasks:
      - name: Execute the script
        ansible.builtin.command:
          cmd: "python3 /etc/openvpn/EasyRSA/revoke_ovpn_cert.py --username {{ username }} --slack_token {{ slack_token }} --ca_key_password {{ ca_key_password }}"
          chdir: /etc/openvpn/EasyRSA
        register: revoke_cert_output
        
      - debug: msg="{{ revoke_cert_output }}"
    
      
