---
- name: List EasyRSA pki certifcate files
  hosts: all
  gather_facts: no

  tasks:
    - name: Find files in /etc/openvpn/EasyRSA/pki/issued folder
      find:
        paths: "/etc/openvpn/EasyRSA/pki/issued"
        recurse: no
        file_type: file
      register: openvpn_files

    - name: Display list of file names
      debug:
        msg: "{{ openvpn_files.files | map(attribute='path') | map('basename') | list | sort }}"
