---
- name: List EasyRSA pki certifcate files
  hosts: all
  gather_facts: no

  tasks:
    - name: Find files in /etc/openvpn/EasyRSA/pki/issued folder
      find:
        paths: "/etc/openvpn/EasyRSA/pki/issued"
        recurse: no
        file_type: file
      register: openvpn_files

    - name: Display contents of openvpn_files variable
      debug:
        var: openvpn_files
